### ISSUE TITLE
Question concerning Full-Disk-Encryption guide

### ISSUE THREAD

**Issue by szaimen** [noobient/noobuntu#84]
Hey, 
thanks for the great guide concerning FDE and TPM2 unlock:
https://github.com/noobient/noobuntu/wiki/Full-Disk-Encryption#tpm-2

Do you know if this could work on Ubuntu 20.04 or does this only apply to noobuntu?

Thanks for any answer!

**Comment by bviktor** [comment]
Hi,

Yes, it does work on 20.04, but I haven't tried the Clevis/TPM packages from the Ubuntu repo, I recompiled everything from sources like on 18.04. The scripts are here:

https://github.com/noobient/noobuntu/tree/master/share

The built packages are here:

https://nexus.noobient.com/#browse/browse:noobuntu-focal

The relevant Ansible part is here:

https://github.com/noobient/noobuntu/blob/master/ansible/roles/devenv/tasks/main.yml#L27

**Comment by szaimen** [comment]
Hi, thanks for this! Do you have any idea how to add the pre-built packets to an ubuntu installation?

I guess this should be good for the gpg key:
`wget -qO - https://apt.noobient.com/files/noobuntu.asc | sudo apt-key add -`
But how do I add the package to apt sources? thanks!

**Comment by szaimen** [comment]
Hey, sry for getting on your nerves. 
I've succesfully tested the setup procedure on Ubuntu 20.04 LTS with the packages from the ubuntu repo.
What I was missing is that at least those packets have to be installed:
`clevis-tpm2 clevis-luks clevis-initramfs`
Maybe you could add a hint in this wiki article in which you state that at least those are needed?

Also I used `update-initramfs -u -k 'all' to update initramfs`, but don't know if that makes any difference.

**Comment by bviktor** [comment]
Uh, those are the stock Ubuntu packages with different package names. To use my packages, put

```
deb [arch=amd64] https://apt.noobient.com/noobuntu-focal/ focal main
```

into `/etc/apt/sources.list.d/noobuntu.list`. To me, `update-initramfs -u` was not sufficient, I needed `update-initramfs -c`.

**Comment by szaimen** [comment]
Thanks! For me the question is resolved! 👍
